dist: trusty
os: linux
sudo: required
language: java
jdk: openjdk11

services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - name: "Clean"
      script: ./mvnw clean
    - name: "Test"
        script: ./mvnw test
    - name: "Package"
        script: ./mvnw package
    - name: "Docker build & push"
      script: bash ./scripts/docker_ci.sh

before_install:
  - chmod +x ./mvnw
  - chmod +x ./scripts/docker_ci.sh

# keep the maven local repository between different runs
cache:
  directories:
    - $HOME/.m2

# enable or disable notifications
notifications:
  email: false
