dist: trusty
os: linux
sudo: required
language: java
jdk: openjdk11

services:
  - docker

# stages names from jobs
stages:
  - clean
  - test
  - package

jobs:
  include:
    - name: "Clean"
      stage: clean
      install: true
      script: ./mvnw clean
    - name: "Test"
        stage: test
        install: true
        script: ./mvnw test
    - name: "Package"
        stage: package
        install: true
        script: ./mvnw package
    - name: "Docker build & push"
      script: bash ./scripts/docker_ci.sh

before_install:
  - chmod +x ./mvnw
  - chmod +x ./scripts/docker_ci.sh

# keep the maven local repository between different runs
cache:
  directories:
    - $HOME/.m2

# enable or disable notifications
notifications:
  email: false
